spring:
    application:
        name: th_proj
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mybatis_proj_db
        username: root
        password: 1234
    mvc:
        hiddenmethod:
            filter:
                enabled: true

mybatis:
     configuration:
         map_underscore-to-camel-case: true
     mapper-locations: mapper/**/*.xml